
var helper2;
document.addEventListener("DOMContentLoaded", function () {
    var textContainer2 = document.getElementById("textHeaderContainerHomeID2");
    textContainer2.style.color = '#ededed';
    textContainer2.style.fontSize = "1rem";
    textContainer2.style.zIndex = "1";
    textContainer2.style.fontFamily = "Fantasy , Arial, Helvetica, sans-serif";
    textContainer2.style.letterSpacing = '4rem';
    textContainer2.style.position = 'absolute';
    textContainer2.innerText = "ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ENTRADOX ROBOTICS ";
    textContainer2.classList.add('headerHorizontalMoveAnim');
    helper2 = textContainer2;
    addText2();
});


function addText2() {
    var text = helper2.innerText;
    
    helper2.innerText = text + " " + text;
}

// Call the addText function periodically to add more text
setInterval(addText2, 60000); // You can adjust the interval as needed

